## cachematrix.R

## Create two functions which working together can calculate
## the inverse of a matrix and cache it for quick access next time
## saving computation time

## makeCacheMatrix()
##      Create a special vector of four functions for a matrix
##      that the functions can be used to access the matrix itself and its inverse.
##      the four functions are:
##      1. set(): set the matrix stored in the vector to a new value and reinitiate the inverse
##      2. get(): get the matrix stored in the vector
##      3. setinverse(): assign a value to the inverse. Mainly used by 'caceSolve()' function
##      4. getinverse(): get the inverse stored in the vector
##
## Args: 
##      'x' is the matrix to be stored and inversed
##
## Returns: 
##      A "vector" which is a list of functions
##      that caches a matrix and its inverse 
makeCacheMatrix <- function(x = matrix()) {      
        inversed_matrix <- NULL                      ## initiate the inversed matrix as NULL
        set <- function(y){                          ## 'y' is the new matrix to be stored in the vector, 
                x <<- y                              ## assign it to 'x', the ols matrix stored
                inversed_matrix <<- NULL             ## clear the old inverse stored
        }
        get <- function() x
        setinverse <- function(inverse) inversed_matrix <<- inverse
        getinverse <- function() inversed_matrix
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)                ## return a vector containing the functions to access the matrix and its inverse
}

## cacheSolve()
##      calc or get the inverse matrix from the 'special matrix'
##      which is the vector generated by makeCacheMatrix()
##
## Args: 
##      'x' is the vector generated by makeCacheMatrix that store a matrix and its inverse
## Returns:
##      the inverse of the matrix,
##      generated by either compute or callback from the cache 
cacheSolve <- function(x, ...) {   
        inversed_matrix <- x$getinverse()
        if(!is.null(inversed_matrix)){               ## if the inverse already exists
                message("getting cached data")       ## print a message and
                return(inversed_matrix)              ## get it out from the cache
        }
        regular_matrix <- x$get()                    ## otherwise, get the regular matrix from the vector
        inversed_matrix <- solve(regular_matrix)     ## compute the inverse
        x$setinverse(inversed_matrix)                ## put the reuslt back into the vector for quick access
        inversed_matrix                              ## return the inversed matrix      
}
